### ISSUE TITLE
Instance of GTStylerVisitor DNU #visitIpfsWikiLinkAnnotation:

### ISSUE THREAD

**Issue by seandenigris** [khinsen/WikiForGToolkit#1]
It happened as soon as I completed the Pillar annotation in the screenshot...
<img width="1202" alt="Screen Shot 2020-09-04 at 3 35 38 PM" src="https://user-images.githubusercontent.com/184176/92279089-95a76e00-eec4-11ea-9ee1-af275ff6541a.png">

**Comment by khinsen** [comment]
Should be fixed by https://github.com/khinsen/WikiForGToolkit/commit/c8b9477bd3879d35d553c7d6eb3cfdd616c2e958. I had forgotten to migrate an extension method from the IPFS package, so it worked only when IPFS was loaded as well.
