### ISSUE TITLE
Clicking twice on page list gives error

### ISSUE THREAD

**Issue by seandenigris** [khinsen/WikiForGToolkit#4]
<img width="206" alt="Screen Shot 2020-09-08 at 12 10 12 PM" src="https://user-images.githubusercontent.com/184176/92501293-592d8800-f1cc-11ea-9c68-4f2a91ab9347.png">

`Can not add child that is already added to another element`

**Comment by khinsen** [comment]
I can confirm this issue. Looks like this is related to how the dropdown menu is handled. Will require some debugging...
