### ISSUE TITLE
Error when completing wiki page keyword in Wiki Browser

### ISSUE THREAD

**Issue by seandenigris** [khinsen/WikiForGToolkit#6]
`Instance of GtDocumenter did not understand #when:send:to:for:`

**Comment by khinsen** [comment]
Could you give some more details? That message is sent nowhere in my code, so it must happen somewhere in GToolkit, but I don't see where and when.

I suppose you are typing an annotation referring to a wiki page, right? That's `${w`, at which point you should get the proposition `wikiPage`. Then `:` and you should see `name=` as a proposition. At which of these two points do the get the exception?

**Comment by seandenigris** [comment]
I get the error when I compete the annotation e.g. `}$`

**Comment by khinsen** [comment]
I have never seen that. It points to some problem with the rendering code in a Wiki annotation, and that makes me wonder if you still have the old `APWikiLinkAnnotation` class around. It would compete with the new `WkWikiLinkAnnotation` because both claim the same tag `wikiPage`.

**Comment by seandenigris** [comment]
Ah, yes that's probably it. I had both loaded. Let's close for now.
